package corterm

// List of constant for translation
const (
	Username    = "username"
	Password    = "password"
	Resources   = "resources"
	Name        = "name"
	Language    = "language"
	Email       = "email"
	Property    = "property"
	Value       = "value"
	ID          = "ID"
	Description = "description"
	Created     = "created"
	Updated     = "updated"
	Deleted     = "deleted"
	List        = "list"
	Fields      = "fields"
	Type        = "type"
	Code        = "code"
	Scope       = "scope"
	Notes       = "notes"
	Profile     = "profile"
	Status      = "status"
	Message     = "message"
	Messages    = "messages"
	Tag         = "tag"
	Tags        = "tags"

	VCreatedSuccessfully = "%v created successfully"
	VUpdatedSuccessfully = "%v updated successfully"
	VDeletedSuccessfully = "%v deleted successfully"
	ListOfV              = "list of %v"
	TemporaryToken       = "temporary token"
	VInfo                = "%v info"
)
