package eacterm

const (
	Symbol                    = "symbol"
	Currency                  = "currency"
	Currencies                = "currencies"
	Transaction               = "transaction"
	Transactions              = "transactions"
	LastYearCounter           = "last year counter"
	Slot                      = "slot!"
	Slots                     = "slots!"
	TempSlots                 = "temporary slots"
	Journal                   = "journal"
	Voucher                   = "voucher"
	ApproveVoucher            = "approve voucher"
	DifferenceIsNotZeroV      = "difference is not zero %v"
	Asset                     = "asset"
	Cash                      = "cash"
	Equity                    = "equity"
	Capital                   = "capital"
	UpdateBalance             = "update balance"
	TransactionTypeIsNotValid = "transaction type is not valid"
	Rate                      = "rate"
	Rates                     = "rates"
	BalanceSheet              = "balance sheet"
	ThereIsNoCurrencyRate     = "there is no currency rate, please enter rates to continue"
	PostDate                  = "post date"
	CurrencyID                = "currency ID"
)
