package corerr

// List of all errors for record in the app
const (
	InternalServerError                  = "internal server error"
	RouteNotFound                        = "route not found"
	Unauthorized                         = "unauthorized"
	PleaseReportErrorToProgrammer        = "please report error to the programmer"
	RecordVVNotFoundInV                  = "record %v:%v not found in %v"
	RecordNotFound                       = "record not found"
	VisNotValid                          = "%v is not valid"
	BindFailed                           = "bind failed"
	ValidationFailed                     = "validation failed"
	VisRequired                          = "%v is required"
	MinimumAcceptedCharacterForVisV      = "minimum accepted character for %v is %v"
	MaximumAcceptedCharacterForVisV      = "maximum accepted character for %v is %v"
	AcceptedValueForVareV                = "accepted value for %v are: [%v]"
	DuplicateHappened                    = "duplicate happened"
	SomeVRelatedToThisVSoItIsNotV        = "some %v related to this %v so it is not %v"
	ErrorBecauseOfForeignKey             = "error because of foreign key"
	VWithValueVAlreadyExist              = "%v with value %v already exists"
	VisAlreadyExist                      = "%v is already exist"
	ErrorInBindingV                      = "error in binding %v"
	InvalidID                            = "invalid id"
	InvalidVForV                         = "invalid %v for %v"
	YouDontHavePermission                = "you don't have permission"
	TokenIsRequired                      = "token is required"
	TokenIsNotValid                      = "token is not valid"
	TokenIsExpired                       = "token is expired"
	VNotExist                            = "%v not exist"
	ForbiddenToVV                        = "forbidden to %v %v"
	Forbidden                            = "forbidden"
	VisInactive                          = "%v is inactive"
	MinimumAcceptedValueForVisV          = "minimum accepted value for %v is %v"
	MaximumAcceptedValueForVisV          = "maximum accepted value for %v is %v"
	VShouldntLessThanV                   = "%v shouldn't be less than %v"
	VShouldntMoreThanV                   = "%v shouldn't be more than %v"
	VHasChildThereforeNotDeleted         = "%v has child, therefore not deleted"
	VIsConnectedToAVVPleaseDeleteItFirst = "%v is connected to a %v:%v, please delete it first"
	NeedDataToBeInserted                 = "need data to be inserted"
	YouDontHavePermissionToThisV         = "you don't have permission to this %v"
	PleaseLoginAgain                     = "please login again"
)
